version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - "15672"
    restart: always
    networks:
      - clientnetwork
    

  orchestrator:
    build: orchestrator
    volumes:
      - ./orchestrator:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 80:80
    networks:
      - clientnetwork

  slave:
    build: slave
    volumes:
      - ./slave:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - clientnetwork

  master:
    build: master
    volumes:
      - ./master:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - clientnetwork

  Zookeeper:
    image: 'zookeeper'
    ports:
      - 2181:2181
    restart: always
    networks:
      - clientnetwork

networks:
  clientnetwork:
    driver: bridge

